# Generated by Django 4.0.4 on 2022-05-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_menuitem_price_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cover',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
