# Generated by Django 4.0.4 on 2022-08-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_menuitem_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='Имя')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('message', models.TextField(blank=True, verbose_name='Введите сообщение')),
            ],
            options={
                'verbose_name': 'Входящее сообщение',
                'verbose_name_plural': 'Входящие сообщения',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиции'},
        ),
    ]
