# Generated by Django 4.0.4 on 2022-08-14 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_incomingmessage_alter_menuitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название информ. категории')),
                ('description', models.TextField(default='-', verbose_name='Описание')),
                ('position', models.IntegerField(default=0)),
                ('type_inform_cat', models.CharField(max_length=10, verbose_name='Тип блока "banner/menu"')),
            ],
            options={
                'verbose_name': 'Информ. Категория',
                'verbose_name_plural': 'Информ. Категории',
            },
        ),
        migrations.AlterField(
            model_name='incomingmessage',
            name='message',
            field=models.TextField(verbose_name='Введите сообщение'),
        ),
        migrations.AlterField(
            model_name='incomingmessage',
            name='name',
            field=models.CharField(max_length=12, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название позиции'),
        ),
        migrations.CreateModel(
            name='InformBlockMenuContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('weight', models.IntegerField(default=0)),
                ('price_float', models.FloatField(default=0.0)),
                ('informCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.informcategory')),
            ],
            options={
                'verbose_name': 'Контент меню',
                'verbose_name_plural': 'Контент меню',
            },
        ),
    ]
