# Generated by Django 4.0.4 on 2022-08-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_informcategory_alter_incomingmessage_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Меню - Категория', 'verbose_name_plural': 'Меню - Категории'},
        ),
        migrations.AlterModelOptions(
            name='informblockmenucontent',
            options={'verbose_name': 'Информ. Контент меню', 'verbose_name_plural': 'Информ. Контент меню'},
        ),
        migrations.AlterModelOptions(
            name='informcategory',
            options={'verbose_name': 'Информ - Категория', 'verbose_name_plural': 'Информ - Категории'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Меню - Позиция', 'verbose_name_plural': 'Меню - Позиции'},
        ),
        migrations.AddField(
            model_name='informblockmenucontent',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
