# Generated by Django 4.0.4 on 2022-08-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmessage',
            name='answered',
            field=models.BooleanField(default=False, verbose_name='Отвечено'),
        ),
        migrations.AddField(
            model_name='incomingmessage',
            name='phone',
            field=models.IntegerField(default=375, verbose_name='Phone'),
        ),
    ]
