# Generated by Django 4.0.4 on 2022-08-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_incomingmessage_answered_incomingmessage_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmessage',
            name='phone',
            field=models.CharField(default='+375', max_length=12, verbose_name='Phone'),
        ),
    ]
