# Generated by Django 4.0.4 on 2022-08-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_incomingmessage_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmessage',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Phone'),
        ),
    ]
